# Generated by Django 4.1.7 on 2023-03-31 10:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StudentMainModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('dob', models.DateField()),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], max_length=100)),
                ('image', models.ImageField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='StudentMarksModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marks', models.IntegerField()),
                ('sem', models.CharField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8)], max_length=100)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student', to='app_student.studentmainmodel')),
            ],
        ),
        migrations.CreateModel(
            name='studentMarksMainModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('branch', models.CharField(choices=[('MECH', 'MECH'), ('CSC', 'CSC'), ('ECE', 'ECE'), ('IT', 'IT'), ('CIVIL', 'CIVIL')], max_length=100)),
                ('marks', models.ManyToManyField(related_name='student_marks', to='app_student.studentmarksmodel')),
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='student_name', to='app_student.studentmainmodel')),
            ],
        ),
    ]
