# Generated by Django 4.1.7 on 2023-03-31 12:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_student', '0002_alter_studentmainmodel_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentmarksmodel',
            name='student',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='student', to='app_student.studentmainmodel'),
        ),
    ]
